### ISSUE TITLE
Nox makes viewing area larger than the display

### ISSUE THREAD

**Issue by eatondpe** [calrobertlee/roam-css-styles#11]
You know how much I love your Nox theme. Today I discovered an issue I hope you can help with.

### Background
I've been looking for some CSS that would prevent the text edit area in Roam from extending beyond the bottom of the screen. As it is, the cursor position drops out of view as I'm typing, causing me to stop typing so I can scroll to bring the cursor position back into view.

### Today I discovered
Today I noticed that the last item on a list of pages in the right sidebar could not be brought into view if I had something expanded that caused it to drop below the bottom of the screen. I was unable to scroll down far enough to bring that last item into view.

For whatever reason, I decided to turn off Nox. I was curious about how some color coding I added might look on a light background. (I chose the colors to look good on a dark background.) And what I saw was that without Nox, that bottom page in the sidebar could always be brought into view by scrolling.

I ran a second test in the main (center) pane. I began typing, and when I reached the end of the line the page scrolled down one line to keep the cursor in the viewable screen.

I haven't found where in Nox this might be set. But this anomaly occurs only when Nox is active.

Can you help?

**Comment by calrobertlee** [comment]
Thanks for bringing this my attention! I really appreciate your clear message, it helped.

This was the line that had the issue:
`.roam-body-main.flex-h-box[style*="height: calc(100% - 45px);"] {
    height: calc(100% + 45px) !important;
}`

I've changed it to:
`.roam-body-main.flex-h-box[style*="height: calc(100% - 45px);"] {
    height: calc(100%) !important;
}`

If you are interested, this bit of code compensates for the moved topbar.  Since we moved the topbar to the right, the height of the entire app lost 45 pixels.  Roam must have recently changed something which invalidated the previous code.

If you notice anything else, please do let me know!

Thanks again,
Cal

**Comment by eatondpe** [comment]
Thanks, Cal. I knew I could count on you to reveal what I was missing.

I recommend your work frequently. Not merely because of its superior quality, but because I believe in you.
________________________________
