### ISSUE TITLE
new blockquotes are just white space

### ISSUE THREAD

**Issue by alok** [calrobertlee/roam-css-styles#16]
css doesn't seem to support block quotes at least in Nox

**Comment by d9ifxw3yev** [comment]
Quick fixes for:

* block quotes
* inline references
* new search path function
* search on top right
* font selection alignment
* etc. (see top comments)

```
/* align font families */
html,
div,
textarea,
.rm-pm-editor h1,
.rm-pm-editor h2,
.rm-pm-editor h3,
.rm-level1,
.rm-level2 {
  font-family: var(--main-font) !important;
}

/* hide Roam logo */
#roam-sidebar-logo {
  display: none !important;
}

/* uppercase DB name */
.rm-db-title {
  text-transform: uppercase !important;
}

/* default editor font size */
.roam-block-container {
  font-size: 18px;
}

/* block path & inline references */
.rm-search-path,
.rm-inline-references {
  background-color: var(--left-sidebar-bg);
}
.rm-inline-references,
.rm-search-path-heading,
.rm-h,
.rm-zoom-item,
.rm-zoom-path,
.rm-zoom-full-path {
  color: var(--popover-font-color);
}

/* blockquote color */
.rm-bq {
  background-color: var(--codemirror-bg);
}

/* tag color */
.rm-page-ref-tag,
.rm-page-ref-tag:hover {
  color: var(--main-font-color) !important
}
```

**Comment by calrobertlee** [comment]
Hi @alok thanks for bringing this to my attention! and thank you @d9ifxw3yev this is really useful

**Quick question: the block quote you two are referring to is using this command, correct?**
`:hiccup [:blockquote "foo bar"]
`

Because on my end there doesn't seem to be an issue. You might be on an older version of Nox and would need to use this code for the new CSS:
`@import url('https://calrobertlee.github.io/roam-themes/nox.css');`

But, please let me know if I misunderstood and are talking about something else.

Thanks again!

**Comment by d9ifxw3yev** [comment]
You can do native markdown style blockquotes with `>` at the beginngon for a line now 🥰

**Comment by calrobertlee** [comment]
That's awesome! Wasn't aware this was just added.  Thanks again for the code it works perfectly :)
